name: GitHub Release

on:
  push:
    tags:
      - "*"

jobs:
  github_release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Create GitHub release
#        uses: softprops/action-gh-release@v1
#        with:
#          draft: false
#          generate_release_notes: true
