name: Changelog

on:
  push:
    branches:
      - main
    paths:
      - .changeset/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Create CHANGELOG file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            package.json

      - name: Install dependencies
        run: npm ci

      - name: Create Pull Request with Changelog
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "Prepare next release"
          title: "Bump version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
