name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.release.outputs.published }}
      publishedPackages: ${{ steps.release.outputs.publishedPackages }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            package.json

      - name: Install dependencies
        run: npm ci

      - name: Create Release Pull Request or Tag
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version
          publish: npm run tag
          commit: "Prepare next release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
